### ISSUE TITLE
Repeating fields not saving values

### ISSUE THREAD

**Issue by DrakeRichards** [DrakeRichards/roll20-character-sheets#1] opened 2022-10-25 00:29 UTC
Issue reported by roll20 user Spektri: https://app.roll20.net/forum/post/11151047/infinity-2d20/?pageforid=11155582#post-11155582

> some brackets just dont work and when player (or GM) closes a sheet, it will loose some data (weapons, talent names and such)

**Comment by DrakeRichards** [comment] 2022-10-25 01:18
Added commit 51706874638324cd7aac87f94942d4addd13d2dd to address the possible cause for this issue, but was unable to reproduce it on my test sheets. Will need specific examples to continue troubleshooting.

**Comment by roblally** [comment] 2022-10-25 21:04
I hope this helps:

Steps to reproduce:

1. Browser - Chrome, up-to-date.
2. Create new roll20 game using Infinity 2d20.
3. Create new character.
4. Go to Gear tab.
5. In Gear sub-section, click the Add button under name.
6. Add an item with the name One.
7. Add an item with the name Two.
8. Add an item with the name Three.
9. Close the sheet.
10. Reopen the sheet.
11. The item named One is missing. There is a blank line, but the text is missing.

Additional notes: The Add button seems to be unreliable. Sometimes it works, sometimes it doesn't. Sometimes you need to hit it twice. Sometimes an item appears and then disappears when focus changes.

(And thanks again for your work here. I appreciate it.)

**Comment by DrakeRichards** [comment] 2022-10-25 21:16
@roblally That's perfect, thank you! I was able to reproduce this and confirmed that it's being caused by blank fields crashing the migration script. The commits in my most recent pull request (Roll20/roll20-character-sheets/pull/11147) will fix this.

**Comment by DrakeRichards** [comment] 2022-10-25 22:14
@roblally I think the issue with having to click the “Add” button twice on repeating fields is something with roll20 itself. I was getting the same issue in the old character sheet, and I don’t have any scripts or CSS that affect those buttons at all. I’ll do a bit more digging and file an Issue in the main repository if it is on them.

**Comment by roblally** [comment] 2022-10-26 17:23
> @roblally That's perfect, thank you! I was able to reproduce this and confirmed that it's being caused by blank fields crashing the migration script. The commits in my most recent pull request ([Roll20/pull/11147](https://github.com/Roll20/roll20-character-sheets/pull/11147)) will fix this.

Your commits have been merged in, and I tried out the issue and it seems to be fixed. 

Thanks again!

**Closed as completed** 2022-10-26 17:24 UTC
